name: flutter_tutorials
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_hooks: ^0.20.5
  # google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  # go_router: ^14.2.1
  gap: ^3.0.1

  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  # cloud_firestore: ^4.14.0
  # firebase_storage: ^11.4.1

  # http: ^1.2.1
  # universal_html: ^2.2.4
  # flutter_stripe: ^10.2.0
  # uuid: ^4.4.2
  # flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  # assets:
  #   - .env
  #   - assets/images/
