// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlmyLxb79abv5wzSVWMD0MUuu2iLedfIM',
    appId: '1:714374888824:web:dfddbbfda915b71d059c8d',
    messagingSenderId: '714374888824',
    projectId: 'flutter-tutorials-bf941',
    authDomain: 'flutter-tutorials-bf941.firebaseapp.com',
    storageBucket: 'flutter-tutorials-bf941.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUGe8ia2p8N-D8i13vz-HmVGoyOXVgF-k',
    appId: '1:714374888824:android:3928c4ad41eac8cd059c8d',
    messagingSenderId: '714374888824',
    projectId: 'flutter-tutorials-bf941',
    storageBucket: 'flutter-tutorials-bf941.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTcCQ1kDIbxg_6-edTopd2x-hmPgXpThE',
    appId: '1:714374888824:ios:ba9a31afadb52d02059c8d',
    messagingSenderId: '714374888824',
    projectId: 'flutter-tutorials-bf941',
    storageBucket: 'flutter-tutorials-bf941.appspot.com',
    iosBundleId: 'com.chenkuochou.flutterTutorials',
  );
}
